# [START cloudbuild]
steps:
# This step creates a role.
- name: 'gcr.io/cloud-builders/kubectl'
  id: Create Role
  args:
  - 'apply'
  - '-f'
  - 'role.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-south1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=secondary'
# This step creates binds role.
- name: 'gcr.io/cloud-builders/kubectl'
  id: Apply Role
  args:
  - 'apply'
  - '-f'
  - 'applyRole.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-south1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=secondary'
# This step deploys the container image.
- name: 'gcr.io/cloud-builders/kubectl'
  id: Deploy App
  args:
  - 'apply'
  - '-f'
  - 'kubernetes-deployment.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-south1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=secondary'
# This step deploys the service.
- name: 'gcr.io/cloud-builders/kubectl'
  id: Deploy Service
  args:
  - 'apply'
  - '-f'
  - 'kubernetes-service.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-south1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=secondary'
  # This step deploys the service.
- name: 'gcr.io/cloud-builders/kubectl'
  id: Deploy Virtual Service
  args:
  - 'apply'
  - '-f'
  - 'mongo-virtualservice.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-south1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=secondary'
# [END cloudbuild]
