apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodejs-store
    tier: db
  name: nodejs-store-mongodb
spec:
  ports:
   - name: mongo-port
     port: 27017
     targetPort: 27017
  clusterIP: None
  selector:
    app: nodejs-store
    tier: db
