apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
 name: mongo-virtual-service
spec:
 hosts:
 - nodejs-store-mongodb
 gateways:
 - mesh
 tcp:
 - route:
   - destination:
       host: nodejs-store-mongodb.default.svc.cluster.local
       port:
         number: 27017